{
 "title": "Access Logs GitHub",
 "tags": [
  "access-logs",
  "monitoring"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prefix", "query": "${VAR_PREFIX}" },
   { "name": "scraper_job_name", "query": "${VAR_SCRAPER_JOB_NAME}" },
   {
    "name": "URI",
    "query": "label_values($prefix:lines_parsed_total, request_uri)"
   },
   {
    "name": "Environment",
    "query": "label_values($prefix:lines_parsed_total, environment)"
   },
   { "name": "avgwinsize", "label": "Avg Window Size", "query": "30s,1m,2m,5m,10m,30m" }
  ]
 },
 "panels": [
  {
   "title": "Requests/sec",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum($prefix:lines_parsed_per_second{request_uri=~\"$URI\",environment=~\"$Environment\",job=\"$scraper_job_name\"})"
    }
   ]
  },
  {
   "title": "Time (min)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "min($prefix:request_time_seconds_per_second{request_uri=~\"$URI\",environment=~\"$Environment\",job=\"$scraper_job_name\"} > 0)"
    }
   ]
  },
  {
   "title": "Time ($avgwinsize avg min)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(rate($prefix:request_time_seconds_total{request_uri=~\"$URI\",environment=~\"$Environment\",job=\"$scraper_job_name\"}[$avgwinsize]) > 0)"
    }
   ]
  },
  {
   "title": "Bandwidth (in)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 0 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum($prefix:received_bytes_per_second{request_uri=~\"$URI\",environment=~\"$Environment\",job=\"$scraper_job_name\"})"
    }
   ]
  },
  {
   "title": "Scraper Last Started",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"$scraper_job_name\"}*1000"
    }
   ]
  },
  {
   "title": "Tracked Metrics",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "scraper_active_metrics{job=\"$scraper_job_name\"}"
    }
   ]
  },
  {
   "title": "Bandwidth In",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 0 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(in_bytes_total{environment=~\"$Environment\", job=\"$scraper_job_name\"}[1m]))"
    }
   ]
  },
  {
   "title": "Requests/sec ($avgwinsize avg)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate($prefix:lines_parsed_total{request_uri=~\"$URI\",environment=~\"$Environment\",job=\"$scraper_job_name\"}[$avgwinsize]))"
    }
   ]
  },
  {
   "title": "Time (avg)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 2 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg($prefix:request_time_seconds_per_second{request_uri=~\"$URI\",environment=~\"$Environment\",job=\"$scraper_job_name\"} > 0)"
    }
   ]
  },
  {
   "title": "Time ($avgwinsize avg)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 2 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(avg_over_time($prefix:request_time_seconds_per_second{request_uri=~\"$URI\",environment=~\"$Environment\",job=\"$scraper_job_name\"}[$avgwinsize]) > 0)"
    }
   ]
  },
  {
   "title": "Bandwidth (out)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 2 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum($prefix:sent_bytes_per_second{request_uri=~\"$URI\",environment=~\"$Environment\",job=\"$scraper_job_name\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"$scraper_job_name\"}[1m])*100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 2 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$scraper_job_name\"}"
    }
   ]
  },
  {
   "title": "Requests Visible",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase($prefix:lines_parsed_total{request_uri=~\"$URI\",environment=~\"$Environment\",job=\"$scraper_job_name\"}[${__range_s}s]))"
    }
   ]
  },
  {
   "title": "Time (max)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 4 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "max($prefix:request_time_seconds_per_second{request_uri=~\"$URI\",environment=~\"$Environment\",job=\"$scraper_job_name\"} > 0)"
    }
   ]
  },
  {
   "title": "Time ($avgwinsize avg max)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 4 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(rate($prefix:request_time_seconds_per_second{request_uri=~\"$URI\",environment=~\"$Environment\",job=\"$scraper_job_name\"}[$avgwinsize]) > 0)"
    }
   ]
  },
  {
   "title": "Parser Errors ($avgwinsize avg)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate($prefix:parser_errors_total{job=\"$scraper_job_name\"}[$avgwinsize]))"
    }
   ]
  },
  {
   "title": "User Agents",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase($prefix:lines_parsed_total{request_uri=~\"$URI\",environment=~\"$Environment\",job=\"$scraper_job_name\"}[${__range_s}s])) by(user_agent)",
     "legendFormat": "{{user_agent}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "reqps", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum($prefix:lines_parsed_per_second{request_uri=~\"$URI\",environment=~\"$Environment\",job=\"$scraper_job_name\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "min($prefix:request_time_seconds_per_second{request_uri=~\"$URI\",environment=~\"$Environment\",job=\"$scraper_job_name\"} > 0)",
     "legendFormat": "Time (min)"
    },
    {
     "expr": "max($prefix:request_time_seconds_per_second{request_uri=~\"$URI\",environment=~\"$Environment\",job=\"$scraper_job_name\"} > 0)",
     "legendFormat": "Time (max)"
    },
    {
     "expr": "avg($prefix:request_time_seconds_per_second{request_uri=~\"$URI\",environment=~\"$Environment\",job=\"$scraper_job_name\"} > 0)",
     "legendFormat": "Time (avg)"
    },
    {
     "expr": "max(rate($prefix:request_time_seconds_total{request_uri=~\"$URI\",environment=~\"$Environment\",job=\"$scraper_job_name\"}[$avgwinsize]))",
     "legendFormat": "Time (win avg max)"
    },
    {
     "expr": "sum(rate($prefix:lines_parsed_total{request_uri=~\"$URI\",environment=~\"$Environment\",job=\"$scraper_job_name\"}[$avgwinsize]))",
     "legendFormat": "Requests (win avg)"
    }
   ]
  },
  {
   "title": "URIs",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase($prefix:lines_parsed_total{request_uri=~\"$URI\",environment=~\"$Environment\",job=\"$scraper_job_name\"}[${__range_s}s])) by(request_uri) > 0",
     "legendFormat": "{{request_uri}}"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "-sum($prefix:sent_bytes_per_second{request_uri=~\"$URI\",environment=~\"$Environment\",job=\"$scraper_job_name\"})",
     "legendFormat": "Out"
    },
    {
     "expr": "-sum(rate($prefix:sent_bytes_total{request_uri=~\"$URI\",environment=~\"$Environment\",job=\"$scraper_job_name\"}[$avgwinsize]))",
     "legendFormat": "Out (win avg)"
    },
    {
     "expr": "sum($prefix:received_bytes_per_second{request_uri=~\"$URI\",environment=~\"$Environment\",job=\"$scraper_job_name\"})",
     "legendFormat": "In"
    },
    {
     "expr": "sum(rate($prefix:received_bytes_total{request_uri=~\"$URI\",environment=~\"$Environment\",job=\"$scraper_job_name\"}[$avgwinsize]))",
     "legendFormat": "In (win avg)"
    }
   ]
  },
  {
   "title": "Remote Addresses (except localhost)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 14 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase($prefix:lines_parsed_total{request_uri=~\"$URI\",environment=~\"$Environment\",job=\"$scraper_job_name\",remote_addr!=\"localhost\",remote_addr!=\"127.0.0.1\",remote_addr!=\"::1\"}[${__range_s}s])) by(remote_addr)",
     "legendFormat": "{{remote_addr}}"
    }
   ]
  },
  {
   "title": "Users",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 14 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase($prefix:lines_parsed_total{request_uri=~\"$URI\",environment=~\"$Environment\",job=\"$scraper_job_name\"}[${__range_s}s])) by(remote_user)",
     "legendFormat": "{{remote_user}}"
    }
   ]
  },
  { "title": "Per URI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "$URI",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 19 },
   "repeat": "URI",
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum($prefix:lines_parsed_per_second{request_uri=~\"$URI\",environment=~\"$Environment\",job=\"$scraper_job_name\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(rate($prefix:lines_parsed_total{request_uri=~\"$URI\",environment=~\"$Environment\",job=\"$scraper_job_name\"}[$avgwinsize]))",
     "legendFormat": "Requests (win avg)"
    }
   ]
  }
 ]
}